In [ ]:
import pandas as pd

In [ ]:
df =pd.read_csv('/content/Task.csv')

In [ ]:
df

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
df.head()

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Country    10 non-null     object
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes

In [ ]:
df.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [ ]:
df.value_counts('Age')

Age
27.0    1
30.0    1
35.0    1
37.0    1
38.0    1
40.0    1
44.0    1
48.0    1
50.0    1
Name: count, dtype: int64

In [ ]:
df.head()

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [ ]:
df['Age']=df['Age'].fillna(df['Age'].mean())

In [ ]:
df['Salary']=df['Salary'].fillna(df['Salary'].mean())

In [ ]:
df.isnull().sum()

Country      0
Age          0
Salary       0
Purchased    0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Country    10 non-null     object
 1   Age        10 non-null     float64
 2   Salary     10 non-null     float64
 3   Purchased  10 non-null     object
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes

In [ ]:
df['Age']=df['Age'].astype(int)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Country    10 non-null     object
 1   Age        10 non-null     int64
 2   Salary     10 non-null     float64
 3   Purchased  10 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 448.0+ bytes

In [ ]:
df['Salary']=df['Salary'].astype(int)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Country    10 non-null     object
 1   Age        10 non-null     int64
 2   Salary     10 non-null     int64
 3   Purchased  10 non-null     object
dtypes: int64(2), object(2)
memory usage: 448.0+ bytes

In [ ]:
df.head()

   Country  Age  Salary Purchased
0   France   44   72000        No
1    Spain   27   48000       Yes
2  Germany   30   54000        No
3    Spain   38   61000        No
4  Germany   40   63777       Yes

In [ ]:
df['Purchased'].replace({'No':0 , 'Yes':1},inplace=True)

<ipython-input-24-c8c079d0312a>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Purchased'].replace({'No':0 , 'Yes':1},inplace=True)

In [ ]:
df.head()

   Country  Age  Salary  Purchased
0   France   44   72000          0
1    Spain   27   48000          1
2  Germany   30   54000          0
3    Spain   38   61000          0
4  Germany   40   63777          1

In [ ]:
df['Country'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [ ]:
df['Country'].replace({'France':1 , 'Spain':2 , 'Germany':3},inplace=True)

<ipython-input-30-ffb623d560a7>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Country'].replace({'France':1 , 'Spain':2 , 'Germany':3},inplace=True)

In [ ]:
df.head()

   Country  Age  Salary  Purchased
0        1   44   72000          0
1        2   27   48000          1
2        3   30   54000          0
3        2   38   61000          0
4        3   40   63777          1

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Country    10 non-null     int64
 1   Age        10 non-null     int64
 2   Salary     10 non-null     int64
 3   Purchased  10 non-null     int64
dtypes: int64(4)
memory usage: 448.0 bytes